### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by donbowen** [sizhewanglehigh/3guys#1]
Ok, understanding layoffs. Fun idea.

Your project has two goals:
1. Understanding the drivers of layoffs. 
2. Seeing how the market reacts to layoffs.

Your revised proposal needs 
1. To make these dual goals clearer 
2. Dive deeper into what each needs. (This requires clarity in the structure and formatting of the document, not tiny tweaks)
3. Writing upgrades. 

Drivers of layoffs:
- You have no stated hypotheses for this part of the project
- You're going to use some variables extracted from news articles, ok
- You don't explain how you'll get and add macro economic factors to the dataset 
- Same for firm performance variables. These variables must *pre date* the news story. Maybe decline in firm sales? Some other ideas should come easily. 

Market stock price reaction:
- You reversed the hypotheses: H0 is the null (no relationship expected)
- You have no discussion of the dataset for this portion
- The dataset for this portion of the project will be different than the drivers portion! It will look like the midterm's data in my solution: firm, event_date, date, event_time, return, excess return
- This part of your project is called an "event study". The "key output" looks like this:
    ![image](https://user-images.githubusercontent.com/50885867/232811828-63f467ee-9f41-491a-99e6-a12ba4fd0c93.png)
- This is basically the average (excess) return for firms, grouped by event_time, with error bars
- See the example code below to replicate a similar figure. You can adapt this. 

---

```python
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt

#### load data

# set seed for reproducibility
np.random.seed(123)

# create dataframe with 4 events and event times from -4 to 4
df = pd.DataFrame({
    'event_id': ['A', 'B', 'C', 'D'] * 9,
    'event_time': sorted(list(range(-4, 5)) * 4)
})

# generate normally distributed returns for each event time and a potential control var
df['returns'] = np.random.normal(0, 1, size=len(df))
df['someX'] = np.random.normal(0, 1, size=len(df))

#### plot returns in event time (reg version)

# run the regression
model   = smf.ols(formula='returns ~ C(event_time,Treatment(reference=-1))', data=df)
results = model.fit()

# extract the coefficients and confidence intervals
fig, ax            = plt.subplots(figsize=(8, 6))
coef_table         = results.conf_int(alpha=0.05)
coef_table['coef'] = results.params
coef_table.columns = ['lower', 'upper', 'coef']

# the reg table's categorical names stink: C(event_time, Treatment(reference=-1))[T.-4]
# lets rename them to the right level
def categorical_relabel(varname,reference_label):
    try:
        return int(varname.split('[T.')[1].split(']')[0])
    except:
        return reference_label
   
coef_table['event_time'] = coef_table.index.map(lambda x: categorical_relabel(x, -1))

# plot
coef_table.plot(kind='scatter', x='event_time', y='coef', ax=ax, s=100)
ax.errorbar(coef_table['event_time'], coef_table['coef'], yerr=[coef_table['coef'] - coef_table['lower'], coef_table['upper'] - coef_table['coef']], fmt='none', color='black')
plt.title('Returns')
plt.xlabel('Event Time')
plt.ylabel('Excess Returns')
ax.axhline(y=0, color='gray', linestyle='--')
plt.show()
```

**Comment by sizhewang1130** [comment]
These are how we change in our updated proposal:
- restate the research questions 
- clarity each steps, including some details
- clarity what final dataset should include
- provide a sample of final dataset

**Comment by sizhewang1130** [comment]
@donbowen 

Hi Don,

Can we get our update proposal feedback? Thank you.

Best,
Sizhe Wang
